### ISSUE TITLE
conda installation issue

### ISSUE THREAD

**Issue by wwood** [urmi-21/orfipy#3] opened 2020-12-10 00:33 UTC
Hi,

Small thing, when running orfipy on a gzip fastq file I ran into this:
```
Traceback (most recent call last):
  File "/home/ben/e/orfipy-0.0.2/bin/orfipy", line 11, in <module>
    sys.exit(main())
  File "/home/ben/e/orfipy-0.0.2/lib/python3.8/site-packages/orfipy/__main__.py", line 338, in main
    orfipy.findorfs.main(infile,
  File "/home/ben/e/orfipy-0.0.2/lib/python3.8/site-packages/orfipy/findorfs.py", line 479, in main
    seqs = Fasta(infasta)
  File "/home/ben/e/orfipy-0.0.2/lib/python3.8/site-packages/pyfaidx/__init__.py", line 996, in __init__
    self.faidx = Faidx(
  File "/home/ben/e/orfipy-0.0.2/lib/python3.8/site-packages/pyfaidx/__init__.py", line 354, in __init__
    raise ImportError(
ImportError: BioPython >= 1.73 must be installed to read block gzip files.
```

I suppose this can be fixed by specifying a biopython version constraint in the conda definition?
Thanks.

**Comment by urmi-21** [comment] 2020-12-10 18:05
Hi @wwood,
Thanks for your feedback. The issue is actually not related to Conda or Biopython.
Currently, orfipy uses pyfaidx to index and read fasta files and .gz compressed files are not supported. If you want to work with compressed files then files must be compressed using [bgzip](http://www.htslib.org/doc/bgzip.html), as this format is recognized by pyfaidx.

The other issue is that currently, orfipy doesn't have support for fastq files, only fasta format is recognized. I can provide support for fastq in a future release (in fact it is already on my to-do list). For now, the workaround for you might be to [convert fastq to fasta](https://bioinformaticsworkbook.org/dataWrangling/fastaq-manipulations/converting-fastq-format-to-fasta.html#gsc.tab=0) and then use orfipy.

I will close this issue. Feel free to reopen if you have more comments/suggestions.

**Comment by wwood** [comment] 2020-12-10 21:07
Right, except that this error would also occur for a bgzip'd fasta input, as I understand.

**Comment by urmi-21** [comment] 2020-12-11 01:32
Ok, I was assuming pyfaidx took care of bgzip but yea you are correct I need to list biopython as a dependency. I will take care of this in the next release.

**Comment by urmi-21** [comment] 2020-12-12 23:47
added biopython as a requirement https://github.com/urmi-21/orfipy/commit/370bb026310edfbcd4368106caae78c9f7bf95e0

**Closed as completed by urmi-21** 2020-12-12 23:47 UTC
